// flow-typed signature: 611f59f2d43cb2dc39c95314a8cfaa48
// flow-typed version: <<STUB>>/react-app-rewire-aliases_v^0.2.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-aliases'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-aliases' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-aliases/index' {
  declare module.exports: $Exports<'react-app-rewire-aliases'>;
}
declare module 'react-app-rewire-aliases/index.js' {
  declare module.exports: $Exports<'react-app-rewire-aliases'>;
}
